const LINES = [
  'phdude - the senior researcher in your terminal',
  '',
  'Usage: phdude <command> [options]',
  '',
  'Commands:',
  '  init [dir]                        create a research workspace here or in <dir>',
  '  bootstrap                         ingest, detect packs, then hand off to the agent',
  '  ingest [paths...]                 inventory, hash and extract sources/ (default)',
  '  status                            project, inventory, knowledge, conflicts, decisions',
  '  next                              the highest-impact next action, with reasons',
  '  knowledge list|show|trace         query the knowledge graph',
  '  add <type>                        add claim, evidence, fact, source, question,',
  '                                    hypothesis, method, result or artifact-role',
  '  link <id> --to <id>…              attach evidence, questions or artifacts to an object',
  '  decide propose|approve|reject|supersede',
  '                                    research decisions; the researcher decides',
  '  promote <id> --decision <DEC-id>  move an object to canonical',
  '  cite list|check|export            citation registry: list, verify, export BibTeX/CSL',
  '  research "<query>"|list|show|accept|dismiss',
  '                                    search the literature; review what came back',
  '           [--question RQ-n] [--provider p,p] [--from YYYY] [--limit N]',
  '           [--type t] [--approve-preprint] [--reason "…"]',
  '           [--allow-network]        nothing leaves the machine unless the policy allows it',
  '  research-fresh [--question RQ-n]  re-run the searches that have gone stale',
  '                 [--all] [--allow-network]',
  '  freshness                         last search per question, age per source, what is stale',
  "  edit <id> --json '<fields>'       correct the non-identity fields of a non-canonical object",
  '  matrix [--format md|csv]          literature matrix: one row per source',
  '         [--question RQ-n]          (optionally filtered to a research question)',
  '  gaps                              research gaps: questions, claims, sources, conflicts',
  '  health [--save] [--trend]         Research Health: eight explainable dimensions, the',
  '                                    observations behind each score, and the trend',
  '  data add <path>|list|show <id>|profile <id>',
  '                                    register a file under data/ as a dataset: hash, format',
  '                                    and a deterministic column profile',
  "  analyze add --json '<decl>'       declare an analysis: a script under analysis/, the",
  '                                    datasets it reads, and where it leaves results.json',
  '          list|show <id>|runs <id>  what is declared, and every run of one analysis',
  '          run <id> [--allow-exec]   run it and record the RESULTs; refuses when the inputs',
  '              [--force]             have not changed since the last successful run',
  '  table add --json|list|show <id>|build <id>',
  '                                    render a result or a dataset as Markdown, LaTeX and CSV',
  '        [--format md,latex,csv,xlsx,docx]',
  '                                    under tables/out/, recording what it read; a build whose',
  '        [--force]                   source has not moved reports up to date and writes nothing.',
  '                                    xlsx needs no tool; docx needs pandoc',
  '  present outline [--from manuscript|claims]',
  '          [--profile <venue>] [--force]  slides from the approved sections, or from the',
  '                                    claims the evidence supports; PPTX too, with pandoc',
  '  template list|add <path>|use <name> --for <venue>|check <name>',
  '           [--kind docx|pptx|latex]  register the DOCX, PPTX and LaTeX templates a build',
  '                                    renders through, and check a DOCX has the styles',
  '  figure add --json|list|show <id>|build <id>|check',
  '                                    declare a figure with alt text, build it through its',
  '         [--allow-exec] [--force]   generator, and report what has gone stale',
  '  repro check                       what every analysis, table and figure would need re-run',
  '                                    or rebuilt, and which input moved',
  '  prose <section> | --file <path>   academic prose quality report: six scores, located',
  '        [--lang c]                  observations, and what to do about each one',
  '  write <section> [--voice id]      assemble the writing context and the draft contract',
  '        [--budget chars]            for one section; writes cache, never prose',
  '  deslop <section> [--file f]       the revision contract for a section, or a revision',
  '         [--allow-additions]        through the gates, meaning preservation included',
  '  manuscript init|list|show <s>|status',
  '                                    the manuscript: sections, their status, the approvals',
  '             submit <s> --file f [--revision] [--allow-additions]',
  '                                    run the writing gates over a draft and record it',
  '             approve <s> --decision DEC-id | reopen <s>',
  '                                    approve a section, or reopen an approved one',
  '  authors list|show|add|learn|consensus',
  '                                    per-researcher voice profiles, learned from samples',
  '  packs list|detect|apply <name>    field, method and venue packs',
  '  profile list|show|check|use <venue>',
  '                                    venue profiles: what the venue expects, what the',
  '        [--profile <venue>]         manuscript does not meet yet, and which one it targets',
  '  build [--format md|docx|pdf|latex|html]',
  '                                    build the manuscript from its approved sections;',
  '        [--profile <venue>]         a build whose inputs have not moved writes nothing',
  '        [--sections a,b] [--include-drafts] [--force]',
  '  adapt --to <venue> [--apply]      what moving the manuscript to another venue would take:',
  '                                    section mapping, word-limit deltas, figure formats and',
  '                                    terminology; --apply writes manuscript.<venue>.yaml',
  '  review <kind>|submit|list|show|accept|dismiss|resolve',
  '                                    assemble a bounded review context for methodology,',
  '         [--target <id|manuscript:<s>|project>]',
  '         [--budget chars]           reviewer2, reproducibility, citation or custom, and',
  '         submit --file f [--kind k] record what the reviewer found as REVIEW objects',
  '         list [--status s] [--kind k] | show <id> | accept|dismiss|resolve <id> [--reason "…"]',
  '  mode lite|full|ruthless|off       set the review mode',
  '  skills list|install <path|url>|remove <name>',
  '                                    the agent skills this workspace loads; install copies an',
  '         [--allow-network] [--force]  external skill under the same permissions as a shipped one',
  '  migrate [--dry-run] [--force]     upgrade the workspace to the current schema version',
  '  doctor                            adapters, cache, schema versions, git state',
  '  help                              show this message',
  '',
  'Global options:',
  '  --json                            machine-readable output',
  '  --workspace <dir>                 run against another workspace',
  '  --actor researcher=<name>,agent=<host>',
  '                                    override the recorded actor',
  '  --version                         print the version',
  '',
  'Exit codes: 0 ok, 1 usage, 2 validation, 3 policy, 4 external tool missing or a script that failed.',
  'Full reference: docs/cli.md',
];

/**
 * @returns {string}
 */
export function usage() {
  return LINES.join('\n') + '\n';
}

export default async function help() {
  return { text: usage(), json: { usage: usage() } };
}
